### ISSUE TITLE
lab3- css checklist!

### ISSUE THREAD

**Issue by Obarquinho** [Obarquinho/fa22-cse110-lab3#4]
- [x] Comment

- Color

- [x] rgb(r, g,b) or rba(r,g,b,a)
- [x] #FFF or #FFFFFF
- [x] hsl(h, s, l) or hsla(h, s, l, a)
- [x] Color name(i.e 'orange')

- Background

- [x] background-color

- Unit 

- [x] Use 3 unique relative units total
- [x] Use 3 unique absolute units total

- Box Model
- - Margin

- [x] Long(margin-top, margin-bottom, margin-left, margin-right)
- [x] Short(margin: <top> <right> <bottom> <left>)
- [x] Auto margins: margin:auto

- - Padding

- [x] Long(padding-top, padding-bottom, padding-left, padding-right)
- [x] Short(padding:<top><right><bottom><left>)

- - Borders

- [x] border-style
- [x] border-color
- [x] border-width
- [x] border-radius

- Text

- [x] color
- [x] text-decoration
- [x] text-align

- Display

- [x] Experiment with these values: none, block, inline-block, inline. Include at least two of them in your page.
- [x] Apply these values to the display property

- Sizing

- [x] height
- [x] width
- [x] max-width
- [x] min-width

- Position

- [x] 2 of the following values: static, relative, fixed, absolute, sticky (apply these values to the position property

- Pseudo-class

- [x] :hover
- [x] :active

- Layouts
-  - Flexbox

- [x] apply flex to the display property
- [x] Must have more than two children within the element that is using flexbox. Must use minimum three of the flexbox related attributes

- - Grid

- [x] apply grid to the display property
- [x] Must have more than two children within the element that is using the grid. Must use a minimum of three of the grid related attributes

- Responsiveness

- [x] At least one query based on the screen width

- Fonts

- [x] Include and use a 3rd part font. You can load the font in either your HTML or your CSS

**Comment by Obarquinho** [comment]
close!
